<CustomDropDown>:
    Label:
        text: 'item1'
        size_hint_y: None
        height: 44

    Button:
        text: 'item2'
        size_hint_y: None
        height: 44
    Button:
        text: 'item3'
        size_hint_y: None
        height: 44
    Button:
        text: 'item3'
        size_hint_y: None
        height: 44
    Button:
        text: 'item3'
        size_hint_y: None
        height: 44
    Button:
        text: 'item3'
        size_hint_y: None
        height: 44
    Button:
        text: 'item3'
        size_hint_y: None
        height: 44

